package com.email.writer;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatusCode;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;

@Service
@Slf4j
public class EmailGeneratorServices {

    private final WebClient webClient;
    private final ObjectMapper objectMapper;

    @Value("${gemini.api.url}")
    private String baseUrl;

    @Value("${gemini.api.key}")
    private String apiKey;

    public EmailGeneratorServices(WebClient.Builder webClientBuilder, ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
        this.webClient = webClientBuilder.build();
    }

    public String generateEmailReply(EmailRequest emailRequest) {
        String prompt = buildPrompt(emailRequest);

        Map<String, Object> requestBody = Map.of(
                "contents", List.of(
                        Map.of("parts", List.of(
                                Map.of("text", prompt)
                        ))
                )
        );

        try {
            String jsonRequest = objectMapper.writeValueAsString(requestBody);

            // Since we moved the full path to properties, we just append the key
            String fullUri = baseUrl + "?key=" + apiKey;

            log.info("Calling Gemini API: {}", baseUrl);

            String response = webClient.post()
                    .uri(fullUri)
                    .header("Content-Type", "application/json")
                    .bodyValue(jsonRequest)
                    .retrieve()
                    .onStatus(HttpStatusCode::isError, clientResponse -> 
                        clientResponse.bodyToMono(String.class).flatMap(errorBody -> {
                            log.error("Gemini API Error Response: {}", errorBody);
                            return Mono.error(new RuntimeException("API Error: " + errorBody));
                        })
                    )
                    .bodyToMono(String.class)
                    .block();



            return extractResponseContent(response);
        } catch (Exception e) {
            log.error("Error generating email: {}", e.getMessage());
            return "Error generating email: " + e.getMessage();
        }

    }

    private String extractResponseContent(String response) {
        try {
            JsonNode root = objectMapper.readTree(response);
            JsonNode candidates = root.path("candidates");
            
            if (candidates.isArray() && !candidates.isEmpty()) {
                return candidates.get(0)
                        .path("content")
                        .path("parts")
                        .get(0)
                        .path("text")
                        .asText();
            }
            log.warn("Gemini API returned no candidates. Full response: {}", response);
            return "No content generated by AI. This might be due to safety filters or an empty response.";
        } catch (JsonProcessingException e) {
            log.error("Failed to parse JSON response: {}", e.getMessage());
            throw new RuntimeException("Failed to parse AI response", e);
        }
    }

    private String buildPrompt(EmailRequest emailRequest) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("Generate a professional email reply for the following email content. ");
        
        if (emailRequest.getTone() != null && !emailRequest.getTone().isEmpty()) {
            prompt.append("Please use a ").append(emailRequest.getTone()).append(" tone. ");
        }

        prompt.append("\nOriginal Email:\n")
                .append(emailRequest.getEmailContent());

        return prompt.toString();
    }
}